name: kente_codeweaver
description: An educational app teaching coding principles through traditional Kente weaving.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"  # Using the SDK version from the working project

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  flutter_svg: ^2.0.17

  # State management
  provider: ^6.0.5

  # Local storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.0.0-beta.4
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.0.15

  # Environment configuration
  flutter_dotenv: ^5.0.2

  # Networking
  http: ^1.3.0
  
  # Utilities
  intl: any
  url_launcher: ^6.1.11
  uuid: ^4.3.3
  google_generative_ai: ^0.4.6
  
  # Audio and TTS
  just_audio: ^0.9.36
  flutter_tts: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.4
  lints: ^5.1.1
  intl_translation: ^0.20.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    # custom Block engine
    - assets/documents/
    - assets/documents/blocks.json

    # Fonts
    - assets/fonts/

    # Images by category
    - assets/images/achievements/
    - assets/images/blocks/
    - assets/images/characters/
    - assets/images/story/
    - assets/images/tutorial/
    - assets/images/navigation/
    - assets/images/badges/
    - assets/images/patterns/

    # Animations
    - assets/animations/
    
    # Music and sound effects
    - assets/music/

    # Environment configuration
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
    - family: KenteDisplayFont
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
